# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Luminosis 
email: contact@luminosis.org 
description: >- 
    Un jour ma main s'est mise à écrire d'elle même | One day my hand started to write by itself | Our Father | Notre Père
description_fr: >- # this means to ignore newlines until "baseurl:"
  La Vie est la maison de l'Amour, de la Paix et de la Joie. La Vérité enfante les mondes et la Pureté s'en empare pour donner naissance à la Lumière. Ainsi naissent les mondes du Royaume de Notre Père.
description_en: >- # this means to ignore newlines until "baseurl:"
  Life is the home of Love, Peace, and Joy. Truth gives birth to worlds, and Purity seizes them to give birth to Light. Thus are born the worlds of the Kingdom of Our Father.
baseurl: "" # the subpath of your site, e.g. /blog
domain: luminosis.github.io
url: "https://luminosis.github.io/" 
github_username: luminosis 
paginate: 10
lang: en

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
 
twitter_username: luminosisph  
twitter:
  username: luminosisph
  site: "@luminosisph"
  creator: "@luminosisph"
  card: summary
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
